name: Check Rebar Dependencies

on: [pull_request]

jobs:
  check_deps_integrity:
    runs-on: ubuntu-20.04
    container: emqx/build-env:erl23.3.4.9-3-ubuntu20.04

    steps:
      - uses: actions/checkout@v3
      - name: Run check-deps-integrity.escript
        run: ./scripts/check-deps-integrity.escript
