name: Upload release assets
on:
  release:
    types:
      - published

jobs:
  prepare:
    runs-on: ubuntu-20.04
    container: emqx/build-env:erl23.3.4.9-3-ubuntu20.04

    outputs:
      profiles: ${{ steps.detect-profiles.outputs.profiles}}

    steps:
      - uses: actions/checkout@v3
      - id: detect-profiles
        uses: ./.github/actions/detect-profiles

  upload:
    runs-on: ubuntu-20.04
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        profile: ${{fromJSON(needs.prepare.outputs.profiles)}}

    steps:
      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Get packages
        run: |
          if [ "${{ matrix.profile }}"  == "emqx" ];then
              s3dir="emqx-ce"
          else
              s3dir=${{ matrix.profile }}
          fi
          aws s3 cp --recursive  s3://${{ secrets.AWS_S3_BUCKET }}/$s3dir/${{ github.ref_name }} packages
      - uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["packages/*"]'
      - name: update to emqx.io
        run: |
          set -e -x -u
          curl -w %{http_code} \
               --insecure \
               -H "Content-Type: application/json" \
               -H "token: ${{ secrets.EMQX_IO_TOKEN }}" \
               -X POST \
               -d "{\"repo\":\"emqx/emqx\", \"tag\": \"${{ github.ref_name }}\" }" \
               ${{ secrets.EMQX_IO_RELEASE_API }}
      - uses: actions/checkout@v3
      - name: get version
        id: version
        run: echo "version=$(./pkg-vsn.sh)" >> $GITHUB_OUTPUT
      - uses: emqx/push-helm-action@v1
        if: github.event_name == 'release' && endsWith(github.repository, 'emqx') && matrix.profile == 'emqx'
        with:
          charts_dir: "${{ github.workspace }}/deploy/charts/emqx"
          version: ${{ steps.version.outputs.version }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: "us-west-2"
          aws_bucket_name: "repos-emqx-io"
      - uses: emqx/push-helm-action@v1
        if: github.event_name == 'release' && endsWith(github.repository, 'enterprise') && matrix.profile == 'emqx-ee'
        with:
          charts_dir: "${{ github.workspace }}/deploy/charts/emqx-ee"
          version: ${{ steps.version.outputs.version }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: "us-west-2"
          aws_bucket_name: "repos-emqx-io"
      - name: update homebrew packages
        if: github.event_name == 'release' && endsWith(github.repository, 'emqx') && matrix.profile == 'emqx'
        run: |
          if [ -z $(echo $version | grep -oE "(alpha|beta|rc)\.[0-9]") ]; then
              curl --silent --show-error \
                -H "Authorization: token ${{ secrets.CI_GIT_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                -X POST \
                -d "{\"ref\":\"v1.0.3\",\"inputs\":{\"version\": \"${{ github.ref_name }}\"}}" \
                "https://api.github.com/repos/emqx/emqx-ci-helper/actions/workflows/update_emqx_homebrew.yaml/dispatches"
          fi
